-- 코드를 입력하세요
SELECT AUTHOR.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM
(SELECT BOOK.AUTHOR_ID, BOOK.BOOK_ID, BOOK.CATEGORY, BOOK.PRICE * BOOK_SALES.SALES AS TOTAL_SALES
FROM BOOK JOIN 
(SELECT BOOK_ID, SALES
FROM BOOK_SALES
WHERE SALES_DATE LIKE '2022-01%') BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID) AS BOOK_TOTAL_SALES
JOIN AUTHOR ON BOOK_TOTAL_SALES.AUTHOR_ID = AUTHOR.AUTHOR_ID
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR.AUTHOR_ID ASC, CATEGORY DESC