-- 코드를 작성해주세요
SELECT THIRD.ID AS ID
FROM ECOLI_DATA AS THIRD JOIN
(SELECT 
    SECOND.ID AS ID
FROM 
    ECOLI_DATA AS SECOND JOIN
    (SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL) AS FIRST
    ON SECOND.PARENT_ID = FIRST.ID) AS SECOND ON THIRD.PARENT_ID = SECOND.ID
ORDER BY ID ASC
    