-- 코드를 작성해주세요
SELECT T_GEN.ID
FROM 
(SELECT CHILD.*
FROM ECOLI_DATA AS PARENT LEFT JOIN ECOLI_DATA AS CHILD ON PARENT.ID = CHILD.PARENT_ID 
WHERE PARENT.PARENT_ID IS NULL) AS S_GEN LEFT JOIN ECOLI_DATA AS T_GEN ON S_GEN.ID = T_GEN.PARENT_ID
WHERE T_GEN.PARENT_ID IS NOT NULL
ORDER BY T_GEN.ID ASC