-- 코드를 작성해주세요
SELECT ID, IFNULL(CHILD.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS PARENT LEFT JOIN 
(SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
FROM ECOLI_DATA
GROUP BY PARENT_ID) AS CHILD
ON PARENT.ID = CHILD.PARENT_ID
ORDER BY ID ASC
