-- 코드를 입력하세요
SELECT 
    DATE_FORMAT(ALLDATA.SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
    ALLDATA.PRODUCT_ID AS PRODUCT_ID,
    ALLDATA.USER_ID AS USER_ID,
    ALLDATA.SALES_AMOUNT AS SALES_AMOUNT
FROM
(
SELECT ONLINE_SALE_ID , PRODUCT_ID, USER_ID, SALES_AMOUNT, SALES_DATE
FROM ONLINE_SALE AS ONLINE
UNION ALL
SELECT OFFLINE_SALE_ID, PRODUCT_ID, NULL AS USER_ID , SALES_AMOUNT, SALES_DATE
FROM OFFLINE_SALE AS OFFLINE
) AS ALLDATA
WHERE ALLDATA.SALES_DATE LIKE "2022-03%"
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC