
SELECT A.CAR_ID, A.CAR_TYPE, TRUNCATE((1 - P.DISCOUNT_RATE/100) * A.DAILY_FEE * 30, 0) AS FEE
FROM 
    (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR 
    WHERE 
        CAR_ID NOT IN 
        (SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE NOT (START_DATE > '2022-11-30' OR END_DATE < '2022-11-01'))
        and (CAR_TYPE = 'SUV' or CAR_TYPE = '세단')
    ) AS A JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P 
    ON A.CAR_TYPE = P.CAR_TYPE and P.DURATION_TYPE = '30일 이상'
WHERE TRUNCATE((1 - P.DISCOUNT_RATE/100) * A.DAILY_FEE * 30, 0) >= 500000 and TRUNCATE((1 - P.DISCOUNT_RATE/100) * A.DAILY_FEE * 30, 0) < 2000000
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC