-- 코드를 작성해주세요
SELECT 
    ID,
    CASE 
        WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) * 100 <= 25
        THEN 'CRITICAL'
        WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) * 100 <= 50
        THEN 'HIGH'
        WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) * 100 <= 75
        THEN 'MEDIUM'
        WHEN PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) * 100 <= 100
        THEN 'LOW'
    END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID ASC