-- 코드를 입력하세요
SELECT INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS, ROUND(SUM(REVIEW.REVIEW_SCORE) / COUNT(*), 2) AS AVG
FROM REST_INFO AS INFO JOIN REST_REVIEW AS REVIEW ON INFO.REST_ID = REVIEW.REST_ID
WHERE INFO.ADDRESS LIKE "서울%"
GROUP BY INFO.REST_ID
ORDER BY AVG DESC, INFO.FAVORITES DESC