-- 코드를 입력하세요

SELECT CAR_ID, AVAILABILITY
FROM 
(SELECT *, '대여중' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16')

UNION ALL

SELECT *, '대여 가능' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID NOT IN
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16')) AS MERGE
GROUP BY CAR_ID
ORDER BY CAR_ID DESC