-- 코드를 입력하세요
SELECT DR_NAME,DR_ID,MCDP_CD,date_format(HIRE_YMD,"%Y-%m-%d") AS HIRE_YMD
FROM DOCTOR
WHERE DOCTOR.MCDP_CD = 'CS' or DOCTOR.MCDP_CD = 'GS'
ORDER BY DOCTOR.HIRE_YMD DESC, DOCTOR.DR_NAME ASC
