-- 코드를 입력하세요
SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
(SELECT REST_REVIEW.MEMBER_ID, MEMBER_NAME
FROM REST_REVIEW JOIN MEMBER_PROFILE ON REST_REVIEW.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID
GROUP BY REST_REVIEW.MEMBER_ID
ORDER BY COUNT(*) DESC
LIMIT 1) AS A JOIN REST_REVIEW AS B ON A.MEMBER_ID = B.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC