SELECT INFO.ID, NAME_INFO.FISH_NAME, INFO.LENGTH
FROM FISH_INFO AS INFO JOIN FISH_NAME_INFO AS NAME_INFO ON INFO.FISH_TYPE = NAME_INFO.FISH_TYPE
WHERE (INFO.FISH_TYPE, INFO.LENGTH) IN
(SELECT INFO.FISH_TYPE, MAX(LENGTH) AS LENGTH
FROM FISH_INFO AS INFO JOIN FISH_NAME_INFO AS NAME_INFO ON INFO.FISH_TYPE = NAME_INFO.FISH_TYPE
GROUP BY INFO.FISH_TYPE)
ORDER BY INFO.ID