-- 코드를 작성해주세요
SELECT DEPT_ID, DEPT_NAME_EN, ROUND(AVG(SAL), 0) AS AVG_SAL
FROM 
(SELECT HR_D.DEPT_ID, HR_D.DEPT_NAME_EN, SAL
FROM HR_DEPARTMENT AS HR_D JOIN HR_EMPLOYEES AS HR_E ON HR_D.DEPT_ID = HR_E.DEPT_ID) AS A
GROUP BY A.DEPT_ID
ORDER BY AVG_SAL DESC



